---
- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - course.yml
  tasks:
     - name: print course information
       ansible.builtin.debug:
          msg: "Hello {{ COURSE }}, duration: {{ DURATION }}, trainer {{ TRAINER }}"