---
- name: ansible datatypes
  hosts: local
  connection: local
  vars:
   DURATION: 120 # This is number
   COURSE: "Devsecops with aws" # string
   IS_LIVE: true # boolen
   TOOLS: # List
   - Linux
   - shell
   - Ansible
   CONCEPTS: # map or direcotry or object.
    CI: Jenkins
    SCRIPTING: "Shell, Ansible, Terraform, Python"
    tasks:
    - name: print course information
      ansible.builtin.debug:
        msg: "Course is: {{ COURSE }}, Duration: {{ DURATION }}, is live?: {{ IS_LIVE }}, Tools are: {{ TOOLS }}, Concepts are: {{ CONCETPS }}"


